src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $shiping_address;

    /**
     * @ORM\Column(type="integer")
     */
    private $seller_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $base_address;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getShipingAddress(): ?string
    {
        return $this->shiping_address;
    }

    public function setShipingAddress(string $shiping_address): self
    {
        $this->shiping_address = $shiping_address;

        return $this;
    }

    public function getSellerId(): ?int
    {
        return $this->seller_id;
    }

    public function setSellerId(int $seller_id): self
    {
        $this->seller_id = $seller_id;

        return $this;
    }

    public function getBaseAddress(): ?string
    {
        return $this->base_address;
    }

    public function setBaseAddress(string $base_address): self
    {
        $this->base_address = $base_address;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }
}

templates/base.html.twig
{% include 'header.html.twig' %}
    <body>
    {% block body %}    
    	<h2>Тестовое api </h2>
		<ul>
			<li>Покупателю <a href="/buyer/">/buyer/</a></li>
			<li>Продавцу <a  href="/seller/">/seller/</a></li>
			<li>Курьеру <a href="/courier/">/courier/</a></li>
		</ul>    	
        {% endblock %}
        {% block javascripts %}
        <script type="text/javascript">
            function orderGet() {
            axios.get("/order").then(res => {
                console.log(res);
            });
        }
        function orderPut() {
            axios.put("/order",{"Name":"Alex"})
            .then(res => {
                console.log(res);
            })
        }
        function orderDelete() {
            axios.delete("/order", {"Name":"Alex"})
            .then (res => {
                console.log(res);
            })
        }
        orderPut();
        </script>
        {% endblock %}
    </body>
</html>

templates/buyer.html.twig
{%include 'header.html.twig'%}
<h2>Здравствуйте, покупатель</h2>
<form name="order" id="order" action="/order/addOrder" method="POST">
<input name="order[order_name]" placeholder="order id" ></br>
<input name="order[order_shiping_address]" placeholder="your address"></br>
<input name="order[order_buyer_id]" placeholder="your id"></br>
<input name="order[order_product_id]" placeholder="your product id"></br>
<button type="submit">Submit</button>
</form>

templates/buyerForm.html.twig
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.default_shipping_address) }}
    {{ form_row(form.seller_id) }}
    <input type = "submit" name = "submit" value = "Отправить">
    {{ form_end(form) }}

templates/courier.html.twig
<h2>Здравствуйте, курьер</h2>

templates/header.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    </head>

templates/order.html.twig
<h2>Order</h2>
{%if object%}
{%for orders in orders%}
id: {{orders.id}} </br>
name: {{orders.name}} <br/>
shiping_address: {{orders.shipingAddress}} </br>
seller_id: {{orders.sellerId}} </br>
base_address: {{orders.baseAddress}} </br>
product_id: {{orders.productId}}
</br></br></br>
{% endfor%}
{%else%}
{% if orders is empty %}
orders empty
{% else %}
id: {{orders.id}} </br>
name: {{orders.name}} <br/>
shiping_address: {{orders.shipingAddress}} </br>
seller_id: {{orders.sellerId}} </br>
base_address: {{orders.baseAddress}} </br>
product_id: {{orders.productId}}
{% endif %}
{% endif %}

templates/orderForm.html.twig
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.shiping_address) }}
    {{ form_row(form.seller_id) }}
    {{ form_row(form.base_address) }}
    {{ form_row(form.product_id) }}
    <input type = "submit" name = "submit" value = "Отправить">
    {{ form_end(form) }}

templates/orders_delivery_price.html.twig
<h2>Order delivery price</h2>
Отправка из (почтовый индекс ){{ order.baseAddress }} </br>
Доставка в (почтовый индекс) {{ order.shipingAddress }} </br>
Займет следующее расстояние
<a href="https://ru.distance.to/{{order.baseAddress}}/{{order.shipingAddress}}"> 
https://ru.distance.to/{{order.baseAddress}}/{{order.shipingAddress}}
</a>
<br/>
Если интересно, вот пример другого расстояния
<a href="https://ru.distance.to/420014/101000">
https://ru.distance.to/420014/101000
</a>
</br>
</br>
Вот стоимость доставки Почтой России 50г
<a href="https://postprice.ru/engine/russia/api.php?from={{order.baseAddress}}&to={{order.shipingAddress}}&mass=50&valuation=0&month=9&day=23&vat=0&oversized=0&_=1600878610561">
Почта России Доставка
</a>

templates/seller.html.twig
<h2>Здравствуйте, продавец</h2>